version: "3.8"
services:
  d0:
    build: ./d0
    ports:
      - 38500:36000
  d1:
    build: ./d1
    ports:
      - 38401:36000
  d2:
    build: ./d2
    ports:
      - 38402:36000
  wm:
    build: ./wm
    ports:
      - 39876:36000
  daq:
    build: ./daq
    ports:
      - "38999:36000"
